### ISSUE TITLE
mportError: cannot import name 'calinski_harabasz_score' from 'sklearn.metrics' (C:\Users\dkodira\AppData\Roaming\Python\Python37\site-packages\sklearn\metrics\__init__.py)

### ISSUE THREAD

**Issue by cdkodira** [lab-conrad/resVAE#1]
I get this error when I run this:
1
import numpy as np
2
import pandas as pd
3
from resVAE.resvae import resVAE
4
import resVAE.utils as cutils
5
from resVAE.config import config
6
import resVAE.reporting as report
7
​
8
from matplotlib import pyplot as plt
9
import seaborn as sns
10
import os
Using TensorFlow backend.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-715836dd9d2b> in <module>
      1 import numpy as np
      2 import pandas as pd
----> 3 from resVAE.resvae import resVAE
      4 import resVAE.utils as cutils
      5 from resVAE.config import config

~\Documents\Python Scripts\resVAE\resVAE\resvae.py in <module>
     39 import h5py
     40 
---> 41 from sklearn.metrics import calinski_harabasz_score
     42 from keras import constraints
     43 

ImportError: cannot import name 'calinski_harabasz_score' from 'sklearn.metrics' (C:\Users\dkodira\AppData\Roaming\Python\Python37\site-packages\sklearn\metrics\__init__.py)

**Comment by fwten** [comment]
Hi @cdkodira,

Could you check which `sklearn` version are you using? For example, you could do this:
```
import sklearn
print(sklearn.__version__)
```

My guess is that you're using an older version of sklearn (< 0.21), where `metrics.calinski_harabasz_score` is spelled as `metrics.calinski_harabaz_score` (notice the missing 's' in harabaz).

If that is indeed the case, I would recommend you to update your `sklearn` version, otherwise you would have to replace all instances of `harabasz` with `harabaz`.
